name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'reaviz/reaflow'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          version: 18.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build Storybook
        run: npm run build-storybook

      - name: Publish Chromatic
        run: npm run chromatic

      - name: Copy Domain
        run: npm run copy

      - name: Publish Storybook to GH Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: storybook-static
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
